#!/bin/bash

plugin_isupdatable() {
	return 1
}

plugin_isbumpable() {
	return 0
}

plugin_getpkgfiles() {
	updatePkgSums "${PKGDIR}/${PKGNAME}/files"
	echo "${PKGDIR}/${PKGNAME}/files"
}

plugin_bump() {
	local -r PKGREL=$(readSetting "${PKGDIR}"/"${PKGNAME}"/files/PKGBUILD "pkgrel" 0)
	sed -i "s/pkgrel=.*/pkgrel=$((PKGREL+1))/" "${PKGDIR}"/"${PKGNAME}"/files/PKGBUILD
}
